### PR TITLE
Api

### PR DESCRIPTION
**Pull request by KnightWorker37**
Trello: https://trello.com/c/PhZgLcEV/13-api-logic

### CODE REVIEW

**Comment by KnightWorker37** [comment]
[API logic](https://trello.com/c/PhZgLcEV/13-api-logic)

**Comment by emmyobonyo** [comment]
Hello @KnightWorker37, all your checks have failed 😄 . I used linters in order to follow best practices. Kindly read this [documentation](https://github.com/microverseinc/linters-config/tree/master/react-redux).

**Review by emmyobonyo — CHANGES_REQUESTED** [review]
Kindly Fix linter errors. Read this [documentation](https://github.com/microverseinc/linters-config/tree/master/react-redux) for more information

**Comment by KnightWorker37** [comment]
@emmyobonyo please continue with review

**Review by emmyobonyo — APPROVED** [review]

**Pull request merged**
