### PR TITLE
Header

### PR DESCRIPTION
**Pull request by KnightWorker37**
Trello: https://trello.com/c/i8KqloVM/10-header

### CODE REVIEW

**Comment by KnightWorker37** [comment]
[Header](https://trello.com/c/i8KqloVM/10-header)

**Comment by emmyobonyo** [comment]
hello @KnightWorker37. Your stylelint checks returned an error. Kindly run `npx stylelint "**/*.{css,scss}"` to check for errors. Read [React Linters](https://github.com/microverseinc/linters-config/tree/master/react-redux) for more information.

If you don't have time, I can still merge and work on them in the next commit.

**Review by emmyobonyo — CHANGES_REQUESTED** [review]
Hello @KnightWorker37, linter checks are failing :). This [documentation](https://github.com/microverseinc/linters-config/tree/master/react-redux), is a good read

**Comment by KnightWorker37** [comment]
@emmyobonyo please continue with the review

**Pull request merged**
